export const tier4Classes = [
  'Champion',
  'Avenger',
  'White Wizard',
  'Arch Sage',
  'Sniper',
  'Monster Hunter',
  'Phantom Assassin',
  'Master Stalker',
  'Grand Templar',
  'Dark Arch Templar',
  'Hierophant',
  'Prophetess',
  'Professional Witcher',
  'Grand Inquisitor',
  'Summoner',
  'Rune Master',
  'Jounin',
  'Annihilator',
  'Sky Sorceress',
  'Lightbinder',
  'Mystic',
  'Stargazer',
  'Valkyrie',
  'Paladin',
  'Rhapsody',
  'Demon Incarnate',
];

export const allClasses = [
  'Annihilator',
  'Arch Sage',
  'Avenger',
  'Champion',
  'Dark Arch Templar',
  'Demon Incarnate',
  'Grand Inquisitor',
  'Grand Templar',
  'Hierophant',
  'Jounin',
  'Lightbinder',
  'Light Caster',
  'Master Stalker',
  'Monster Hunter',
  'Mystic',
  'Phantom Assassin',
  'Professional Witcher',
  'Prophetess',
  'Rune Master',
  'Sky Sorceress',
  'Sniper',
  'Stargazer',
  'Summoner',
  'White Wizard',
  'Arch Druid',
  'Swordsman',
  'Knight',
  'Crusader',
  'Imperial Knight',
  'Acolyte',
  'Fairy',
  'Sprite',
  'Constellation',
  'Astronomer',
  'Cleric',
  'Priest',
  'Matriarch',
  'Initiate',
  'Mage',
  'Wizard',
  'Sage',
  'Witch Hunter',
  'Slayer',
  'Witcher',
  'Inquisitor',
  'Archer',
  'Hunter',
  'Marksman',
  'Tracker',
  'Druid',
  'Shaman',
  'Shapeshifter',
  'Thief',
  'Rogue',
  'Assassin',
  'Stalker',
  'Templar',
  'Arch Templar',
  'High Templar',
  'Dark Templar',
  'Ninja',
  'Genin',
  'Chunin',
  'Executioner',
  'Novice (Male)',
  'Novice (Female)',
  'Caster',
  'Clairvoyant',
  'Sorceress',
  'Illuminator',
  'Acolyte (M)',
  'Acolyte (F)',
  'Cleric (F)',
  'Valkyrie',
  'Paladin',
  'Rhapsody',
];
