export enum EvoItemRestictions {
  ALL_CLASSES = 0,
  FORGE = 1,
  MELEE = 2,
  MELEE_AGI = 3,
  ALL_EXCEPT_INITIATE = 4,
  INT = 5,
  DRUID = 6,
  SWORDSMAN = 7,
  SW_THIEF = 8,
  SW_THIEF_WH = 9,
  INI_D_ACO = 10,
  ARCHER = 11,
  CHUNIN = 12,
  SHAPESHIFTER = 13,
  INQUISITOR = 14,
  FORGING_MATERIAL = 15,
  HIGH_TEMPLAR = 16,
  AC_CA_FA = 17,
  TANK = 18,
  ULTIMATE_FORGE = 19,
  TEMPLAR_NINJA = 20,
}

export const evoItemRestrictions = {
  '0': 'All classes',
  '1': 'Forge material',
  '2': 'Melee classes only',
  '3': 'Melee agility classes only',
  '4': 'All classes except Initiate',
  '5': 'Intelligence classes only',
  '6': 'Druid class only',
  '7': 'Swordsman class only',
  '8': 'Swordsman, Thief class only',
  '9': 'Swordsman, Thief, Witch Hunter class only',
  '10': 'Initiate, Druid, Acolyte class only',
  '11': 'Archer class only',
  '12': 'Chunin class only',
  '13': 'Shapeshifter class only',
  '14': 'Inquisitor class only',
  '15': 'Forging material',
  '16': 'High Templar class only',
  '17': 'Acolyte, Caster, Fairy class only',
  '18': 'Tank classes only',
  '19': 'Ultimate forge material',
  '20': 'Templar, Ninja class only',
};
